version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: gradle-springboot
    depends_on:
    - docker-mysql
    ports:
    - 8080:8080
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=gBkYntkZ7P8Zs59a
    - DATABASE_NAME=lingua_start_db
    - DATABASE_PORT=3306