version: '3.3'

services:
  lingua-mysql:
    restart: always
    image: mysql:5.7
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lingua_start_db
      MYSQL_USER: lingua_start_user
      MYSQL_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - lingua-mysql-volume:/var/lib/mysql
  lingua-app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    environment:
      DATABASE_HOST: lingua-mysql
      DATABASE_USER: lingua_start_user
      DATABASE_PASSWORD: root
      DATABASE_NAME: lingua_start_db
      DATABASE_PORT: 3306
    volumes:
      - filestorage:/filestorage
    depends_on:
    - lingua-mysql

volumes:
  filestorage:
  lingua-mysql-volume: